import { Concept } from "src/app/common/concept";

export const CONCEPTS: Concept[] = [
    { "label": "apply data imputation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000001" },
    { "label": "Pipe separated values", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000002" },
    { "label": "knowledge of the documenting of the cleaning steps", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000003" },
    { "label": "software review and preservation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000004" },
    { "label": "Repository access", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000005" },
    { "label": "develop FAIR and open research vision", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000006" },
    { "label": "plan stewardship and sharing of FAIR outputs", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000007" },
    { "label": "develop open research strategy and vision", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000008" },
    { "label": "Data management policy", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000009" },
    { "label": "understand research code of conduct", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000010" },
    { "label": "choosing the appropriate reporting guideline for your data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000011" },
    { "label": "data stewardship activity", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000012" },
    { "label": "Data munging", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000013" },
    { "label": "interoperability of digital assets", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000014" },
    { "label": "knowledge of software development", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000015" },
    { "label": "a skills for resource management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000016" },
    { "label": "Preservation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000017" },
    { "label": "data categorisation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000018" },
    { "label": "Data registration", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000019" },
    { "label": "Interoperability", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000020" },
    { "label": "expose your data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000021" },
    { "label": "understanding the requirements of the analysis/research question", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000022" },
    { "label": "aptitudes for workflow technologies management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000023" },
    { "label": "De facto standard", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000024" },
    { "label": "Data entity", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000025" },
    { "label": "Real-time data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000026" },
    { "label": "storage security risk assessment and mitigation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000027" },
    { "label": "Remote access", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000028" },
    { "label": "FAIR stewardship supervising", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000029" },
    { "label": "skills related to high performance computing management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000030" },
    { "label": "FAIR Metrics selection skills", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000031" },
    { "label": "Relational database", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000032" },
    { "label": "Non identifiable data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000033" },
    { "label": "database developer", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000034" },
    { "label": "design", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000035" },
    { "label": "Curation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000036" },
    { "label": "knowledge of applying software", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000037" },
    { "label": "A1. (Meta)data are retrievable by their identifier using a standardised communications protocol", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000038" },
    { "label": "Version control", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000039" },
    { "label": "creating and updating a DMP", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000040" },
    { "label": "understanding FAIR and open research challenges in your organization", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000041" },
    { "label": "ethical application of patents, licenses", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000042" },
    { "label": "Data access protocol", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000043" },
    { "label": "Data processing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000044" },
    { "label": "Data organization", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000045" },
    { "label": "Data rescue", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000046" },
    { "label": "understand societal impact of research", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000047" },
    { "label": "searching via algorithms and software", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000048" },
    { "label": "Audit", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000049" },
    { "label": "wiki site", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000050" },
    { "label": "skills related to authorisation management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000051" },
    { "label": "know metadata standards", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000052" },
    { "label": "storage management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000053" },
    { "label": "Data warehouse", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000054" },
    { "label": "Data driven disaster", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000055" },
    { "label": "Data identifier", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000056" },
    { "label": "Data splitting", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000057" },
    { "label": "manage access", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000058" },
    { "label": "System metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000059" },
    { "label": "tactical/short-term planning", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000060" },
    { "label": "Electronic medical record", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000061" },
    { "label": "aptitudes for provenance information management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000062" },
    { "label": "versioning", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000063" },
    { "label": "aptitudes surrounding the requirements of the analysis/research question", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000064" },
    { "label": "Data modeling", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000065" },
    { "label": "data stewardship planning", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000066" },
    { "label": "use of aggregator sites", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000067" },
    { "label": "Manage metadata catalog", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000068" },
    { "label": "Data transformation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000069" },
    { "label": "Cataloguing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000070" },
    { "label": "design and apply processes for attribution", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000071" },
    { "label": "Dataset series", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000072" },
    { "label": "Data dictionary", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000073" },
    { "label": "Data selection", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000074" },
    { "label": "apply data access policy", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000075" },
    { "label": "discover other peoples data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000076" },
    { "label": "knowledge about data modeling", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000077" },
    { "label": "Documented data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000078" },
    { "label": "conducting operations", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000079" },
    { "label": "Dynamic data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000080" },
    { "label": "Reference model", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000081" },
    { "label": "online workbook", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000082" },
    { "label": "understand mathematical and statistical concepts and techniques relevant to the domain", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000083" },
    { "label": "engaging in open innovation beyond academia", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000084" },
    { "label": "Registered data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000085" },
    { "label": "Integrity", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000086" },
    { "label": "Digital scholarship", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000087" },
    { "label": "a knowledge for resource management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000088" },
    { "label": "a aptitudes for resource management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000089" },
    { "label": "make data actionable for computational prediction of or interpretations from data relevant", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000090" },
    { "label": "knowledge of storage management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000091" },
    { "label": "understand open access publishing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000092" },
    { "label": "use of persistent, resolvable identifiers (PIDs)", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000093" },
    { "label": "Record standardization", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000094" },
    { "label": "online documentation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000095" },
    { "label": "metadata catalogue", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000096" },
    { "label": "understand legal background of patents", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000097" },
    { "label": "Data file format", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000098" },
    { "label": "willingness to help and understand researchers", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000099" },
    { "label": "Data catalogue", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000100" },
    { "label": "skills surrounding the processing of information retrieved from existing sources", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000101" },
    { "label": "Curation workflow", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000102" },
    { "label": "A1.1 The protocol is open, free, and universally implementable", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000103" },
    { "label": "preservation costs management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000104" },
    { "label": "Project manager", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000105" },
    { "label": "publish and release", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000106" },
    { "label": "information security and access management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000107" },
    { "label": "Data production", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000108" },
    { "label": "Raw data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000109" },
    { "label": "skills surrounding applying of tools", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000110" },
    { "label": "be able to make data actionable for computational methods relevant to the data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000111" },
    { "label": "Interface testing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000112" },
    { "label": "Digital object", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000113" },
    { "label": "Digital materials", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000114" },
    { "label": "openness for sharing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000115" },
    { "label": "define access policy", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000116" },
    { "label": "skills related to provenance information management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000117" },
    { "label": "Remote data access", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000118" },
    { "label": "Dissambuation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000119" },
    { "label": "Data compliance", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000120" },
    { "label": "Re-use", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000121" },
    { "label": "trainer/teacher", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000122" },
    { "label": "aptitudes for identity management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000123" },
    { "label": "understand information security challenges", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000124" },
    { "label": "aptitudes for authorisation management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000125" },
    { "label": "govern and assess", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000126" },
    { "label": "Personal information privacy", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000127" },
    { "label": "knowledge of applying of tools", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000128" },
    { "label": "ability to solve fair implementation problems collaboratively", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000129" },
    { "label": "model data structure and define database needs", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000130" },
    { "label": "skills related to cloud computing environment management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000131" },
    { "label": "Data curation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000132" },
    { "label": "cite contributions", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000133" },
    { "label": "Operational management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000134" },
    { "label": "High quality data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000135" },
    { "label": "how to make your data reuseable", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000136" },
    { "label": "I1. (Meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000137" },
    { "label": "Schema", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000138" },
    { "label": "PID service", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000139" },
    { "label": "Foundational interoperability", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000140" },
    { "label": "Data management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000141" },
    { "label": "authorisation management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000142" },
    { "label": "knowledge of authorisation management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000143" },
    { "label": "generate metadata to track transformations.", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000144" },
    { "label": "search repositories and knowledge-bases", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000145" },
    { "label": "Cloud ecosystem", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000146" },
    { "label": "be able to clean data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000147" },
    { "label": "understand legal background of licensing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000148" },
    { "label": "Archive", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000149" },
    { "label": "Trusted Digital Repository", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000150" },
    { "label": "Database administration", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000151" },
    { "label": "knowledge of identity management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000152" },
    { "label": "quality assessment", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000153" },
    { "label": "Data structure", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000154" },
    { "label": "Information technology specialist", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000155" },
    { "label": "Archiving", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000156" },
    { "label": "knowledge of preservation costs management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000157" },
    { "label": "User acceptance testing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000158" },
    { "label": "minimal metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000159" },
    { "label": "metadata creation and exposure", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000160" },
    { "label": "Data destruction", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000161" },
    { "label": "FAIR stewardship training", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000162" },
    { "label": "select metadata standard", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000163" },
    { "label": "process", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000164" },
    { "label": "Creativity", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000165" },
    { "label": "Data table attribute", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000166" },
    { "label": "critical thinking and theory building", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000167" },
    { "label": "Consensus standard", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000168" },
    { "label": "identity management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000169" },
    { "label": "reuse of digital assets", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000170" },
    { "label": "understand sel-archiving", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000171" },
    { "label": "investigate open innovation opportunities", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000172" },
    { "label": "Data recovery", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000173" },
    { "label": "R1. (Meta)data are richly described with a plurality of accurate and relevant attributes", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000174" },
    { "label": "evaluation of repositories for data deposition", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000175" },
    { "label": "Regional standard", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000176" },
    { "label": "workflow technologies management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000177" },
    { "label": "data steward", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000178" },
    { "label": "prepare data for archiving/preservation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000179" },
    { "label": "skills related to preservation costs management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000180" },
    { "label": "repository certification schemes", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000181" },
    { "label": "Registry", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000182" },
    { "label": "recognise and acknowledge contributions", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000183" },
    { "label": "Linked open data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000184" },
    { "label": "Research data format", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000185" },
    { "label": "Research governance", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000186" },
    { "label": "preservation skill", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000187" },
    { "label": "Semantic interoperability", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000188" },
    { "label": "International chemical identifier", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000189" },
    { "label": "Research data publication workflow", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000190" },
    { "label": "Data completeness", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000191" },
    { "label": "Privacy-preserving data linkage", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000192" },
    { "label": "open access publishing and self-archiving", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000193" },
    { "label": "self-archive", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000194" },
    { "label": "Information management advisor", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000195" },
    { "label": "Data management plan", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000196" },
    { "label": "deploy generated models", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000197" },
    { "label": "understand querying techniques", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000198" },
    { "label": "F2. Data are described with rich metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000199" },
    { "label": "R1.1 (Meta)data are released with a clear and accessible data usage license", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000200" },
    { "label": "Data stream", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000201" },
    { "label": "Data librarian", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000202" },
    { "label": "Program governance", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000203" },
    { "label": "aptitudes surrounding data cleaning", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000204" },
    { "label": "File organisation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000205" },
    { "label": "knowledge of workflow technologies management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000206" },
    { "label": "select persistent id. standard", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000207" },
    { "label": "plan data sharing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000208" },
    { "label": "access risk assessment and mitigation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000209" },
    { "label": "Usable data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000210" },
    { "label": "presentation slides", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000211" },
    { "label": "implement secure storage", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000212" },
    { "label": "Data lifecycle", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000213" },
    { "label": "Format and media migration", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000214" },
    { "label": "Data store", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000215" },
    { "label": "design processes for research integrity", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000216" },
    { "label": "core trust seal", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000217" },
    { "label": "Project management lifecycle", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000218" },
    { "label": "Authenticity metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000219" },
    { "label": "researcher", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000220" },
    { "label": "skills related to service level management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000221" },
    { "label": "Personally identifiable information", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000222" },
    { "label": "understand storage security challanges", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000223" },
    { "label": "Normalization", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000224" },
    { "label": "Evaluation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000225" },
    { "label": "Data item", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000226" },
    { "label": "Confidentiality", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000227" },
    { "label": "knowledge of data management costs management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000228" },
    { "label": "logistical support", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000229" },
    { "label": "aptitudes for data management costs management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000230" },
    { "label": "Data acquisition", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000231" },
    { "label": "data management costs management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000232" },
    { "label": "Text file", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000233" },
    { "label": "knows what a DMP is", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000234" },
    { "label": "select the repository for FAIR sharing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000235" },
    { "label": "Human-readable format", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000236" },
    { "label": "data modeling design", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000237" },
    { "label": "Data validation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000238" },
    { "label": "PID record", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000239" },
    { "label": "appreciate importance of research integrity", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000240" },
    { "label": "Structural metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000241" },
    { "label": "know services/conditions of repositories", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000242" },
    { "label": "make data actionable for transformation and integration", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000243" },
    { "label": "Non personally identifiable information", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000244" },
    { "label": "Digitisation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000245" },
    { "label": "generate requirements for services or software", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000246" },
    { "label": "Data publication", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000247" },
    { "label": "findability of digital assets", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000248" },
    { "label": "influencing/community building", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000249" },
    { "label": "Citable data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000250" },
    { "label": "Big data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000251" },
    { "label": "FAIRness assessment", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000252" },
    { "label": "knowledge of the requirements of the analysis/research question", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000253" },
    { "label": "Data archive", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000254" },
    { "label": "Technical metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000255" },
    { "label": "Machine readable", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000256" },
    { "label": "Integrated access management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000257" },
    { "label": "Noisy data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000258" },
    { "label": "FAIR training", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000259" },
    { "label": "Software", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000260" },
    { "label": "prototyping", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000261" },
    { "label": "skills surrounding the documenting of the cleaning steps", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000262" },
    { "label": "Data standardization", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000263" },
    { "label": "Open data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000264" },
    { "label": "data curation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000265" },
    { "label": "plan for data normalisation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000266" },
    { "label": "skills related to funding acquisition management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000267" },
    { "label": "Universally Unique Identifier", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000268" },
    { "label": "build queries", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000269" },
    { "label": "Authentication", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000270" },
    { "label": "Cloud computing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000271" },
    { "label": "appraise", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000272" },
    { "label": "Short-term preservation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000273" },
    { "label": "International standard", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000274" },
    { "label": "Conformance", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000275" },
    { "label": "Data custodian", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000276" },
    { "label": "aptitudes for high performance computing management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000277" },
    { "label": "Manage datasets in a repository", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000278" },
    { "label": "document data-handling workflows", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000279" },
    { "label": "Data de-noising", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000280" },
    { "label": "integrate and analyse", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000281" },
    { "label": "Governance and accountability model", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000282" },
    { "label": "Access", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000283" },
    { "label": "knowledge of project management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000284" },
    { "label": "develop FAIR and open research strategy", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000285" },
    { "label": "patent application", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000286" },
    { "label": "Collection management identification", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000287" },
    { "label": "assess FAIRness", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000288" },
    { "label": "knowledge of change management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000289" },
    { "label": "Data ingestion", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000290" },
    { "label": "Data wrangling", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000291" },
    { "label": "Research data management infrastructure", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000292" },
    { "label": "Flexibility in relating FAIR criteria to openness", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000293" },
    { "label": "choosing the appropriate terminology for your data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000294" },
    { "label": "Structured data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000295" },
    { "label": "knowledge to contextualise FAIR principles to domain", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000296" },
    { "label": "Research data management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000297" },
    { "label": "publish output in a repository", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000298" },
    { "label": "understand persistent id. standards", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000299" },
    { "label": "metadata search via metadata providers", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000300" },
    { "label": "Record provenance information", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000301" },
    { "label": "Data citation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000302" },
    { "label": "skills surrounding software development", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000303" },
    { "label": "knowledge of data cleaning", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000304" },
    { "label": "book", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000305" },
    { "label": "Intellectual leadership", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000306" },
    { "label": "Innovation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000307" },
    { "label": "high performance computing management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000308" },
    { "label": "Provenance", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000309" },
    { "label": "Digital", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000310" },
    { "label": "Analytical quality control", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000311" },
    { "label": "Digital research data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000312" },
    { "label": "ability to critically assess (earlier) work of others and yourself", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000313" },
    { "label": "Managing research", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000314" },
    { "label": "evaluation of how to publish your data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000315" },
    { "label": "Accession number", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000316" },
    { "label": "publish open access", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000317" },
    { "label": "Digital preservation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000318" },
    { "label": "aptitudes surrounding applying of tools", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000319" },
    { "label": "project management activities", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000320" },
    { "label": "knowledge of funding acquisition management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000321" },
    { "label": "manage access control", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000322" },
    { "label": "project management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000323" },
    { "label": "Data retention policy", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000324" },
    { "label": "aptitudes surrounding applying of software", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000325" },
    { "label": "Data representation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000326" },
    { "label": "Metadata dataset", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000327" },
    { "label": "Long-term preservation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000328" },
    { "label": "Research metadata format", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000329" },
    { "label": "Data residency", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000330" },
    { "label": "Information governance", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000331" },
    { "label": "Data element", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000332" },
    { "label": "Data policy", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000333" },
    { "label": "Legacy data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000334" },
    { "label": "Controlled vocabulary", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000335" },
    { "label": "Data integrity", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000336" },
    { "label": "PID attribute", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000337" },
    { "label": "aptitudes for change management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000338" },
    { "label": "Medium-term preservation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000339" },
    { "label": "Project lifecycle", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000340" },
    { "label": "knowledge to relate FAIR data assessment to research community norms", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000341" },
    { "label": "Data traceability", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000342" },
    { "label": "maintaining persistent identifiers", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000343" },
    { "label": "expose and discover", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000344" },
    { "label": "select and apply license", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000345" },
    { "label": "Relations", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000346" },
    { "label": "Dataset", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000347" },
    { "label": "aptitudes for service level management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000348" },
    { "label": "File naming", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000349" },
    { "label": "Extensible Markup Language", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000350" },
    { "label": "skills related to change management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000351" },
    { "label": "Data analysis", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000352" },
    { "label": "resource management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000353" },
    { "label": "Data exploration", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000354" },
    { "label": "aptitudes for storage management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000355" },
    { "label": "advise and mentor", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000356" },
    { "label": "skills related to workflow technologies management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000357" },
    { "label": "Digital infrastructure", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000358" },
    { "label": "skills related to data management cost management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000359" },
    { "label": "PID system", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000360" },
    { "label": "I2. (Meta)data use vocabularies that follow FAIR principles", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000361" },
    { "label": "Cross-disciplinary", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000362" },
    { "label": "data and metadata capture", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000363" },
    { "label": "Semantic data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000364" },
    { "label": "PID domain", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000365" },
    { "label": "skills surrounding applying of software", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000366" },
    { "label": "knowledge to choose FAIR data handling approaches appropriate to the research phenomena", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000367" },
    { "label": "provenance information management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000368" },
    { "label": "computationally predict from or interpret data.", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000369" },
    { "label": "Reproducible research", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000370" },
    { "label": "A1.2 The protocol allows for an authentication and authorisation procedure, where necessary", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000371" },
    { "label": "data stewardship technical concept", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000372" },
    { "label": "Canonical data collection", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000373" },
    { "label": "document code", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000374" },
    { "label": "Data harmonization", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000375" },
    { "label": "Data mart", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000376" },
    { "label": "Access workflow", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000377" },
    { "label": "knowledge of service level management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000378" },
    { "label": "Data model", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000379" },
    { "label": "appreciate security and usability trade-offs", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000380" },
    { "label": "Standard", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000381" },
    { "label": "University teaching", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000382" },
    { "label": "Data migration", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000383" },
    { "label": "Data cleaning", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000384" },
    { "label": "R1.2 (Meta)data are associated with detailed provenance", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000385" },
    { "label": "skills related to project management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000386" },
    { "label": "skills related to identity management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000387" },
    { "label": "using persistent identifiers", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000388" },
    { "label": "database curator", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000389" },
    { "label": "engage innovation partners", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000390" },
    { "label": "R1.3 (Meta)data meet domain-relevant community standards", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000391" },
    { "label": "Data reduction", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000392" },
    { "label": "F4. (Meta)data are registered or indexed in a searchable resource", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000393" },
    { "label": "Data type registry", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000394" },
    { "label": "aptitudes surrounding the documenting of cleaning steps", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000395" },
    { "label": "aptitudes surrounding the processing of information retrieved from existing sources", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000396" },
    { "label": "Database", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000397" },
    { "label": "appreciation of FAIR and open research", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000398" },
    { "label": "ability to learn new techniques for fair implementation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000399" },
    { "label": "aptitudes for funding acquisition management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000400" },
    { "label": "choosing the appropriate model or format for your data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000401" },
    { "label": "provenance metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000402" },
    { "label": "deploy feature data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000403" },
    { "label": "Data availability", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000404" },
    { "label": "willingness to put extra effort into preparing data for long term preservation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000405" },
    { "label": "Data review", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000406" },
    { "label": "appraise and preserve", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000407" },
    { "label": "aptitudes associated with using fair tools and services", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000408" },
    { "label": "build modelling metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000409" },
    { "label": "Preservation metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000410" },
    { "label": "change management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000411" },
    { "label": "knowledge of the processing of information retrieved from existing sources", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000412" },
    { "label": "Original repository", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000413" },
    { "label": "De-identification", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000414" },
    { "label": "Manager", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000415" },
    { "label": "prepare code for archiving/preservation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000416" },
    { "label": "Organizational leadership", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000417" },
    { "label": "Data dredging", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000418" },
    { "label": "skills surrounding the requirements of the analysis/research question", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000419" },
    { "label": "Unstructured data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000420" },
    { "label": "presentation slides with interactive exercises", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000421" },
    { "label": "creating persistent identifiers", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000422" },
    { "label": "Data linkage", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000423" },
    { "label": "aptitudes for project management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000424" },
    { "label": "Catalogue", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000425" },
    { "label": "Funding acquisition management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000426" },
    { "label": "machine access via API", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000427" },
    { "label": "Data structure continuum", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000428" },
    { "label": "skills surrounding data cleaning", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000429" },
    { "label": "Data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000430" },
    { "label": "Semi-structured data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000431" },
    { "label": "book chapter", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000432" },
    { "label": "Research scientist", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000433" },
    { "label": "Digital Object Identifier", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000434" },
    { "label": "F3. Metadata clearly and explicitly include the identifier of the data they describe", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000435" },
    { "label": "analyse requirements for services or software", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000436" },
    { "label": "Information management specialist", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000437" },
    { "label": "A2. Metadata are accessible, even when the data are no longer available", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000438" },
    { "label": "stakeholder engagement on societal impact", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000439" },
    { "label": "documenting the cleaning steps", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000440" },
    { "label": "Principal Investigator", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000441" },
    { "label": "Program manager", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000442" },
    { "label": "Persistent uniform resource locator", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000443" },
    { "label": "data cleaning", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000444" },
    { "label": "Dublin Core", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000445" },
    { "label": "data stewardship guideline", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000446" },
    { "label": "FAIR principle", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000447" },
    { "label": "aptitudes for cloud computing environment management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000448" },
    { "label": "Repurposed data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000449" },
    { "label": "Document type definition", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000450" },
    { "label": "specify metadata and persistent id. standards", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000451" },
    { "label": "I3. (Meta)data include qualified references to other (meta)data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000452" },
    { "label": "Persistent identifier", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000453" },
    { "label": "Scientist", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000454" },
    { "label": "Integration", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000455" },
    { "label": "knowledge of high performance computing management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000456" },
    { "label": "FAIR Mentoring", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000457" },
    { "label": "Data governance", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000458" },
    { "label": "plan", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000459" },
    { "label": "Extensible resource identifier", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000460" },
    { "label": "define database requirements", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000461" },
    { "label": "Impact", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000462" },
    { "label": "Access control list", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000463" },
    { "label": "understand data ownership and access policies", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000464" },
    { "label": "meeting/conference organisation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000465" },
    { "label": "service level management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000466" },
    { "label": "National standard", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000467" },
    { "label": "Open government", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000468" },
    { "label": "access control and management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000469" },
    { "label": "storage security management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000470" },
    { "label": "applying tools", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000471" },
    { "label": "Governance", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000472" },
    { "label": "policies (legal requirements, ethical & FAIR principles)", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000473" },
    { "label": "Open Archives Initiative Protocol for Metadata Harvesting", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000474" },
    { "label": "Computer code", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000475" },
    { "label": "Syntactic interoperability", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000476" },
    { "label": "aptitudes for preservation costs management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000477" },
    { "label": "accessibility of digital assets", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000478" },
    { "label": "cloud computing environment management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000479" },
    { "label": "Corpus", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000480" },
    { "label": "the use of FAIR and open research tools or services knowledge", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000481" },
    { "label": "Data sharing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000482" },
    { "label": "appreciate importance of crediting research contributions", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000483" },
    { "label": "FAIR4S defined activity", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000484" },
    { "label": "Reference resolution", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000485" },
    { "label": "Research manager", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000486" },
    { "label": "Data integration", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000487" },
    { "label": "Standard Operating Procedure", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000488" },
    { "label": "Repository", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000489" },
    { "label": "knowledge of theories underlying FAIR implementation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000490" },
    { "label": "document in lay terms", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000491" },
    { "label": "understanding persistent identifiers", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000492" },
    { "label": "Data upload database", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000493" },
    { "label": "Uniform resource identifier", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000494" },
    { "label": "how to find FAIR research data tools/services (catalogues)", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000495" },
    { "label": "Data reference model", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000496" },
    { "label": "appraise and select repositories for FAIR sharing", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000497" },
    { "label": "Peer review", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000498" },
    { "label": "knowledge of provenance information management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000499" },
    { "label": "Record", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000500" },
    { "label": "De-anonymization", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000501" },
    { "label": "application of fair tools and services", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000502" },
    { "label": "Mandatory standard", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000503" },
    { "label": "Data driven decision management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000504" },
    { "label": "Golden record", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000505" },
    { "label": "processing information retrieved from existing sources", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000506" },
    { "label": "Data quality", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000507" },
    { "label": "using FAIR and open research tools or services", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000508" },
    { "label": "software development", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000509" },
    { "label": "webinar", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000510" },
    { "label": "Digital data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000511" },
    { "label": "F1. (Meta)data are assigned a globally unique and persistent identifier", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000512" },
    { "label": "role", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000513" },
    { "label": "strategic/long-term planning", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000514" },
    { "label": "Data hygiene", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000515" },
    { "label": "Data profiling", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000516" },
    { "label": "Metadata record", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000517" },
    { "label": "Research data", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000518" },
    { "label": "learning medium", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000519" },
    { "label": "data manager", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000520" },
    { "label": "Electronic health record", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000521" },
    { "label": "Data scaling", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000522" },
    { "label": "Access controls", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000523" },
    { "label": "Privacy governance", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000524" },
    { "label": "research integrity, attribution, impact awareness", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000525" },
    { "label": "knowledge of cloud computing environment management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000526" },
    { "label": "Metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000527" },
    { "label": "Comma separated values", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000528" },
    { "label": "identifier", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000529" },
    { "label": "Project team member", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000530" },
    { "label": "Descriptive metadata", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000531" },
    { "label": "github repository", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000532" },
    { "label": "Data mining", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000533" },
    { "label": "data archiving", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000534" },
    { "label": "Encoding schema", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000535" },
    { "label": "ability to apply different perspectives to understand problems/phenomena", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000536" },
    { "label": "Digital archiving", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000537" },
    { "label": "understand data transformation and integration", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000538" },
    { "label": "applying software", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000539" },
    { "label": "PID resolution", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000540" },
    { "label": "skills related to storage management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000541" },
    { "label": "knowledge about data stewardship planning", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000542" },
    { "label": "Data capture", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000543" },
    { "label": "Data repository management", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000544" },
    { "label": "integrate data from disparate data sets", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000545" },
    { "label": "Darwin information typing architecture", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000546" },
    { "label": "Analytics", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000547" },
    { "label": "data stewardship soft skill", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000548" },
    { "label": "aptitudes surrounding software development", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000549" },
    { "label": "document data for archiving/preservation", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000550" },
    { "label": "Machine-readable format", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000551" },
    { "label": "Confidential information", "rdfAbout": "https://github.com/terms4fairskills/FAIRterminology/T4FS_0000552" }]